exclude_patterns:
- "tests/"
- "resources/"
- "storage/"
- ".circleci/"
- ".docker/"
- "src/**/ServiceProvider.php"

plugins:
  phan:
    enabled: true
    config:
      file_extensions: "php"
      ignore-undeclared: true
