version: '2'
services:
  php:
    container_name: gks-php
    image: maartenscholz/gks-php:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www/
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    container_name: gks-nginx
    image: gks/nginx
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    ports:
      - "80:80"
