version: '2'
services:
  php:
    container_name: gks-php
    image: maartenscholz/gks-php:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www/
  nginx:
    container_name: gks-nginx
    image: maartenscholz/gks-nginx:latest
    working_dir: /var/www
    volumes:
      - ./:/var/www/
    ports:
      - "80:80"
  neo4j:
    container_name: gks-neo4j
    build:
      context: ./.docker/neo4j
      dockerfile: Dockerfile
    ports:
      - "7474:7474"
      - "7687:7687"
