# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.json" }}
            - v1-composer
      - restore_cache:
          keys:
            - v1-docker
      - run: if [ -f ./.circleci/cache/gks.tar ]; then docker load -i ./.circleci/cache/gks.tar; fi
      - run: docker-compose up -d --build
      - run: docker save -o ./.circleci/cache/gks.tar gks/php gks/nginx
      - run: docker exec -i gks-php composer install --prefer-dist --no-suggest
      - run: docker exec -i gks-php ./vendor/bin/phpunit
      - save_cache:
          key: v1-composer-{{ checksum "composer.json" }}
          paths:
            - ./vendor
      - save_cache:
          key: v1-docker
          paths:
            - ./.circleci/cache
