version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-composer-{{ checksum "composer.lock" }}
            - v1-composer
      - run: docker-compose up -d
      - run: docker exec -i gks-php composer install --prefer-dist --no-suggest
      - run: docker exec -i gks-php ./vendor/bin/phpunit
      - save_cache:
          key: v1-composer-{{ checksum "composer.lock" }}
          paths:
            - ./vendor
