name: Continuous integration

on:
  push:
    branches:
      - master

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Test
        run: echo 'test'
      - name: Test2
        run: docker-compose -f docker-compose.testing.yml up -d
